### PR TITLE
Update loadDMfile.m

### PR DESCRIPTION
**Pull request by grahamsno**
Rotate and mirror DM files such that they appear correctly

### CODE REVIEW

**Comment by grahamsno** [comment]
That is true and works well for a single image, but fails when trying to
load an image series (both obs = transpose(obs) and obs = obs.').

**Comment by ThFriedrich** [comment]
I suppose the matrix coming from the file is 3-dimensional then? In this case we could permute the matrix. Suppose, we had a stack of images in order [nx, ny, nz] (nz being the stacking dimension), we could probably do something like:
`obs = permute(obs,[2,1,3]);`

**Comment by grahamsno** [comment]
Yes, I tested it on both a single image and an image series and this works as well. `obs = permute(obs, [2 1 3]);`

**Comment by ThFriedrich** [comment]
Great. Thanks a lot for checking on working on this. :) 
Though both implementations produce the same result, I'd recommend updating the pull request accordingly. It may seem a bit petty, but I think there's compelling reasons to avoid functions like `imrotate()` when possible. Mainly, Matlab has no proper version control, not for the core and not for its toolboxes. So any new Matlab release may break the code. The chance they'll change the implementation of something as fundamental as the `permute` function is extremely small though. In this case we can even avoid the dependency on the image-processing toolbox.

**Review by ThFriedrich — APPROVED** [review]

**Pull request merged**
